[package]
name = "cortex-cli"
version = "1.0.0"
edition = "2021"
authors = ["Cortex Team"]
description = "Command-line interface for Cortex programming language"

[[bin]]
name = "cortex"
path = "src/main.rs"

[dependencies]
# Core dependencies
clap = { version = "4.0", features = ["derive", "color"] }
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# File handling
walkdir = "2.0"
glob = "0.3"

# Terminal UI
indicatif = "0.17"
console = "0.15"
colored = "2.0"

# HTTP for package management
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }

# Logging
log = "0.4"
env_logger = "0.10"

# Path handling
pathdiff = "0.2"

[dev-dependencies]
tempfile = "3.0"