[package]
name = "cortex-rust"
version = "0.1.0"
edition = "2021"
authors = ["Cortex Team"]
description = "High-performance AI/ML compiler written in Rust"

[dependencies]
# Lexing and parsing
logos = "0.14"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# CLI interface
clap = { version = "4.0", features = ["derive"] }

# String handling
regex = "1.10"

# Collections
indexmap = "2.0"

# Logging
log = "0.4"
env_logger = "0.10"

# Serialization (for snapshot testing)
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
criterion = "0.5"
insta = { version = "1.40", features = ["yaml"] }

[[bin]]
name = "cortexc"
path = "src/main.rs"
